include /usr/local/etc/PcapPlusPlus.mk

# All Target
all:
	clang++ $(PCAPPP_INCLUDES) -c -o main.o main.cpp
	clang++ $(PCAPPP_LIBS_DIR) -o example-app main.o $(PCAPPP_LIBS)

# Clean Target
clean:
	rm main.o
	rm example-app
